name: Build main
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Project
        run: ./gradlew gitVersion check javadoc -P GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Tag Release
        run: ./gradlew gitTagRelease -P GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Push Tags
        run: git push --tags

      - name: Upload Test Results
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)